### ISSUE TITLE
Logical switch:  bring segment ID into state as computed value.

### ISSUE THREAD

**Issue by rachappag** [IBM-tfproviders/terraform-provider-nsxv#7]
Logical switch ( virtual wire ) segment ID is required while connecting to logical router.
We can save one API call ( GET virtual wire) if we save the segment ID in tf state file.

**Comment by chandidas** [comment]
-1
This will unnecessarily increase the depth of the DLR resource template.

**Comment by rachappag** [comment]
Make sense, will close this enhancement issue.
